routes/admin.php
<?php

Route::get('/', 'DashboardController@handle')->name('dashboard');

Route::prefix('/{resource}')->name('resources.')->group(function() {
    Route::get('/', 'ResourceIndexController@handle')->name('index');
    Route::post('/', 'ResourceStoreController@handle')->name('store');
    Route::get('/create', 'ResourceCreateController@handle')->name('create');

    Route::get('/{resourceId}', 'ResourceShowController@handle')->name('show');
    Route::get('/{resourceId}/edit', 'ResourceEditController@handle')->name('edit');
    Route::put('/{resourceId}', 'ResourceUpdateController@handle')->name('update');
    Route::get('/{resourceId}/attach/{relatedResource}', 'ResourceAttachFormController@handle')->name('attach');
    Route::put('/{resourceId}/attach/{relatedResource}', 'ResourceAttachController@handle')->name('attach');
    Route::delete('/{resourceId}', 'ResourceDestroyController@handle')->name('destroy');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::resource('products', 'ProductController')->only(['index', 'show']);
Route::get('category/{category}', 'ProductController@category')->name('category.show');

// Cart
Route::post('cart/{product}', 'CartController@add')->name('cart.add');
Route::get('cart', 'CartController@show')->name('cart.show');
Route::delete('cart/{product}', 'CartController@remove')->name('cart.remove');

// Orders
Route::get('purchase/address', 'PurchaseController@addressCreate')->name('purchase.address.create');
Route::post('purchase/address', 'PurchaseController@addressStore')->name('purchase.address.store');
Route::get('purchase/success', 'PurchaseController@success')->name('purchase.success');
Route::get('purchase/error', 'PurchaseController@error')->name('purchase.error');
Route::resource('purchase', 'PurchaseController')->only(['store', 'create']);

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Product;
use Configuration;
use Illuminate\Support\Facades\Hash;

class Cart extends Model
{
    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    protected $with = [
        'items',
    ];

    /**
     * The cart items
     *
     * @return Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function items()
    {
        return $this->hasMany('App\CartItem');
    }

    /**
     * The cart's user
     *
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    /**
     * Add a product to the cart
     *
     * @param  $product
     * @param  $quantity
     */
    public function add(Product $product, $quantity = 1)
    {
        if (!$this->exists) {
            $this->save();
        }

        return $this->items()->updateOrCreate(
            ['product_id' => $product->id],
            ['quantity'   => $quantity]
        );
    }

    public function addMany($items)
    {
        if (! $this->exists) {
            $this->save();
        }

        $items = collect($items)->reject(function($item) {
            return $this->hasProductId($item->product_id);
        });

        $this->items()->createMany($items);
    }

    /**
     * Find the product inside the cart
     *
     * @param  App\Product  $product
     * @return App\CartItem
     */
    public function findItem(Product $product)
    {
        if (!$this->exists) {
            return null;
        }

        return $this->items()->where('product_id', $product->id)->first();
    }

    /**
     * Find the product inside the cart
     *
     * @param  App\Product|App\CartItem  $productOrItem
     * @return App\CartItem
     */
    public function remove($productOrItem)
    {
        if (!$this->exists) {
            return null;
        }

        if ($productOrItem instanceof \App\Product) {
            return $this->items()->where('product_id', $productOrItem->id)->delete();
        } else if ($productOrItem instanceof \App\CartItem) {
            return $this->items()->where('id', $productOrItem->id)->delete();
        }
    }

    /**
     * Total price for all the items in the cart item without discount
     *
     * @return float
     */
    public function getTotalAttribute()
    {
        return $this->items->sum('total');
    }

    /**
     * Total price for all the items in the cart item with discount
     *
     * @return float
     */
    public function getDiscountedTotalAttribute()
    {
        return $this->items->sum('discounted_total');
    }

    /**
     * Total price for all the items in the cart item with discount
     *
     * @return float
     */
    public function getDiscountAttribute()
    {
        return $this->items->sum('discount');
    }


    /**
     * Returns if the cart is anonymous
     *
     * @return  bool
     */
    public function isAnonymous()
    {
        return ($this->user_id === null);
    }

    /**
     * Returns if the cart is empty
     *
     * @return  bool
     */
    public function isEmpty()
    {
        return ($this->items->count() === 0);
    }

    /**
     * Returns if the cart is not empty
     *
     * @return  bool
     */
    public function isNotEmpty()
    {
        return !$this->isEmpty();
    }

    /**
     * Returns if the cart reaches the minimum amount
     *
     * @return  bool
     */
    public function reachesMinimumAmount()
    {
        return $this->discounted_total >= static::getMinimumAmount();
    }

    /**
     * Returns the minimum cash amount needed to create an order from this cart
     *
     * @return float
     */
    public static function getMinimumAmount()
    {
        return Configuration::get('CART_MIN', 0);
    }

    public function hasProduct(Product $product)
    {
        return $this->items->contains('product_id', $product->id);
    }

    public function hasProductId($id)
    {
        return $this->items->contains('product_id', $id);
    }

    public function scopeWithTrashedProducts($query)
    {
        return $query->with(['items' => function($query) {
            return $query->withTrashedProduct();
        }]);
    }

    public function getChecksumString()
    {
        return $this->toJson();
    }

    public function checksum()
    {
        return Hash::make($this->getChecksumString());
    }

    public function checkChecksum($checksum)
    {
        return Hash::check($this->getChecksumString(), $checksum);
    }

    public function toOrder()
    {
        return [
            'user_id' => $this->user_id,
        ];
    }
}

app/CartItem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CartItem extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'product_id', 
        'quantity',
    ];

    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    protected $with = [
        'product',
    ];

    /**
     * All of the relationships to be touched.
     *
     * @var array
     */
    protected $touches = ['cart'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'quantity'      => 'decimal:2',
    ];

    /**
     * The associated cart
     * 
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function cart() 
    {
        return $this->belongsTo('App\Cart');
    }

    /**
     * The associated product
     * 
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function product() 
    {
        return $this->belongsTo('App\Product');
    }

    /**
     * Total price for all the items in the cart item without discount
     *
     * @return float
     */
    public function getTotalAttribute()
    {
        return $this->product->price * $this->quantity;
    }

    /**
     * Total price for all the items in the cart item without discount
     *
     * @return float
     */
    public function getDiscountAttribute()
    {
        return $this->product->discount * $this->quantity;
    }

    /**
     * Total price for all the items in the cart item with discount
     *
     * @return float
     */
    public function getDiscountedTotalAttribute()
    {
        return $this->product->discounted_price * $this->quantity;
    }

    /**
     * Returns if the order item has a discount
     *
     * @return bool
     */
    public function getHasDiscountAttribute()
    {
        return ($this->discount_total != 0);
    }

    public function toOrderItem()
    {
        return [
            'price'      => $this->product->price,
            'discount'   => $this->product->discount,
            'product_id' => $this->product_id,
            'quantity'   => $this->quantity,
        ];
    }
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Cart;
use App\Product;
use Illuminate\Http\Request;
use App\Services\CartManager;
use Session;

class CartController extends Controller
{

    /**
     * The cart manager instance
     *
     * @var CartManager
     */
    private $cart;

    /**
     * Creates a new controller instance
     *
     * @param  CartManager  $cart
     */
    public function __construct(CartManager $cart)
    {
        $this->middleware('auth')->only('confirm');

        $this->cart = $cart;
    }


    public function show()
    {
        if ($this->cart->isEmpty()) {
            return view('cart.empty');
        }

        return view('cart.show', [
            'cart'            => $this->cart,
            'recentProducts'  => Product::getRecent(10),
        ]);
    }

    protected function getShippingDate()
    {
        return transform($this->getShippingPeriods(), function($periods) {
            return $periods->first()->resolveDate();
        });
    }

    protected function getShippingPeriods()
    {
        return transform(Auth::user(), function($user) {
            return ShippingPeriod::getShippingPeriods($user);
        });
    }

    public function ajaxEditForm(Product $product, Request $request)
    {
        $item = $this->cart->findItem($product);

        return (!$item)
            ? view('cart.ajax.404')
            : view('cart.ajax.edit', ['item' => $item, 'product' => $item->product]);
    }

    public function remove(Product $product, Request $request)
    {
        $this->cart->remove($product);

        return redirect()->route('cart.show');
    }

    public function add(Request $request, Product $product)
    {
        $request->validate([
            'quantity' => 'nullable|numeric',
        ]);

        $quantity = $request->input('quantity', $product->amount_min);

        $item = $this->cart->add($product, $quantity);

        return $request->input('noshow')
            ? redirect()->route('cart.show')
            : redirect()->route('purchase.create');
    }
}

resources/views/cart/empty.blade.php
@extends('layouts.app')

@section('title', __('Your Cart'))

@section('content')
    <h1>{{ __('Your Cart') }}</h1>
    <div class="text-center my-5">
        <h2 class="d-block">{{ __('Your cart is empty') }}</h2>
        <div>
            <div class="row pt-3 pb-1 justify-content-center">
                <div class="col-auto" style="font-size: 1.3em">
                    <p class="text-center font-weight-bold mb-2" >{{ __("You don't have anything in your cart.") }}</p>
                    <p class="text-center text-muted">{{ __("Why don't you explore our products?") }}</p>
                </div>
            </div>
            <div class="row pt-1 pb-5 justify-content-center">
                <div class="col-auto">
                    <a class="btn btn-primary btn-lg w-auto" href="{{ route('products.index') }}">{{ __('Browse products') }}</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cart/item.blade.php
<tr class="cart_item">
    @isset($editable)
        <td>
            <form method="POST" class="align-middle d-inline" action="{{ route('cart.remove', $item->product) }}">
                @method('DELETE')
                @csrf
                <button type="submit" class="btn btn-outline-danger btn-sm" aria-label="{{ __('Remove product') }}">
                    <i class="material-icons">delete</i>
                </button>
            </form>
        </td>
    @endisset

    <td class="cart-product-thumbnail">
        <a href="{{ route('products.show', $item->product) }}">
            <img class="rounded" width="64" height="64" src="{{ $item->product->thumbImage() }}" alt="{{ $item->product->name }}">
        </a>
    </td>

    <td class="cart-product-name">
        <a href="{{ route('products.show', $item->product) }}">{{ $item->product->name }}</a>
    </td>

    <td class="cart-product-subtotal">
        <span class="amount">
            @include('products.partials.price', ['product' => $item->product])
        </span>
    </td>

    <td class="cart-product-quantity">
        <div class="quantity clearfix">
            {{ ReadableUnit::quantity($item->quantity) }} {{ __('Units') }}
        </div>
    </td>

    <td class="cart-product-subtotal">
        <span class="amount">
            @include('products.partials.itemprice', ['item' => $item])
        </span>
    </td>
</tr>

resources/views/cart/show.blade.php
@extends('layouts.app')

@section('title', __('Your Cart'))

@section('content')

    <h1>{{ __('Your Cart') }}</h1>

    @if (session('error'))
        <div class="alert-error" role="alert">
            <strong>{{ session('error') }}</strong>
        </div>
    @endif

    <div class="clearfix card">
        <div class="card-body row">
            <div class="col-lg-8">
                <h3>{{ __('Your Order') }}</h3>

                @include('cart.table', ['editable' => true])

            </div>
            <div class="col-lg-4 mt-3 mt-md-0">
                <h3>{{ __("Purchase summary") }}</h3>

                @include('cart.summary')
                <p>{{ __("You will can enter the shipping address and in the next step.") }}</p>

            </div>

        </div>

    </div>

    <div class="row clearfix my-3 justify-content-end">
        <div class="col-12 col-lg-4 col-md-6">
            <a href="{!! route('products.index') !!}" class="btn btn-outline-primary btn-lg px-5 w-100">{{ __('Add more products') }}</a>
        </div>
        <div class="col-12 mt-2 col-lg-4 col-md-6 mt-md-0">
            <a href="{{ route('purchase.create') }}" class="btn btn-primary btn-lg px-5 w-100">{{ __('Finish purchase') }}</a>
        </div>
    </div>

    <div class="modal fade" id="edit-quantity-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ __('Update quantity') }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="ajax-content"></div>
            <div class="loading-body">
                <i class="icon-spinner icon-spin"></i>
                <div class="error-alert alert alert-danger">{{ __('There was an error loading the content. Please try again later.') }}</div>
            </div>
        </div>

    </div>

    {{--
    <div class="content-wrap section my-0 py-5">
        <div class="container clearfix">
            <div class="row">
                <div class="col">
                    <h2 class="mb-3">{{ __('Related Products') }}</h4>
                    @include('products.partials.carousel', ['products' => $recentProducts])
                </div>
            </div>
        </div>
    </div>
    --}}

@endsection

resources/views/cart/summary.blade.php
<div class="table-responsive">
    <table class="table cart">
        <tbody>
            <tr class="cart_item">
                <td class="notopborder cart-product-name">
                    <strong>{{ __('Subtotal') }}</strong>
                </td>

                <td class="notopborder cart-product-name">
                    <span class="amount">{{ ReadableUnit::money($cart->total) }}</span>
                </td>
            </tr>

            @if ($cart->has_discount)
                <tr class="cart_item">
                    <td class="notopborder cart-product-name">
                        <strong>{{ __('Discount') }}</strong>
                    </td>

                    <td class="notopborder cart-product-name">
                        <span class="amount">{{ ReadableUnit::money($cart->discount) }}</span>
                    </td>
                </tr>
            @endif

            <tr class="cart_item">
                <td class="cart-product-name">
                    <strong>{{ __('Shipping') }}</strong>
                </td>

                <td class="cart-product-name">
                    <span class="amount">{{ __('Free Shipping!') }}</span>
                </td>
            </tr>

            <tr class="cart_item">
                <td class="cart-product-name">
                    <strong>{{ __('Total') }}</strong>
                </td>

                <td class="cart-product-name">
                    <span class="amount color lead"><strong>{{ ReadableUnit::money($cart->discounted_total) }}</strong></span>
                </td>
            </tr>
        </tbody>
    </table>
</div>

resources/views/cart/table.blade.php
<div class="table-responsive">
    <table class="table cart">
        <thead>
            <tr>
                @isset($editable)
                    <th class="">&nbsp;</th>
                @endisset
                <th class="cart-product-thumbnail">&nbsp;</th>
                <th class="cart-product-name">{{ __('Product') }}</th>
                <th class="cart-product-quantity">{{ __('Unit Price') }}</th>
                <th class="cart-product-quantity">{{ __('Quantity') }}</th>
                @isset($withDelivered)
                    <th class="cart-product-subtotal">{{ __('Delivered') }}</th>
                @endif
                <th class="cart-product-subtotal">{{ __('Total') }}</th>

            </tr>
        </thead>
        <tbody>
            @foreach($cart->items as $item)
                @include('cart.item', [
                    'item' => $item,
                    'editable' => $editable ?? null,
                    'withDelivered' => $withDelivered ?? null,
                ])
            @endforeach
        </tbody>
    </table>
</div>