routes/admin.php
<?php

Route::get('/', 'DashboardController@handle')->name('dashboard');

Route::prefix('/{resource}')->name('resources.')->group(function() {
    Route::get('/', 'ResourceIndexController@handle')->name('index');
    Route::post('/', 'ResourceStoreController@handle')->name('store');
    Route::get('/create', 'ResourceCreateController@handle')->name('create');

    Route::get('/{resourceId}', 'ResourceShowController@handle')->name('show');
    Route::get('/{resourceId}/edit', 'ResourceEditController@handle')->name('edit');
    Route::put('/{resourceId}', 'ResourceUpdateController@handle')->name('update');
    Route::get('/{resourceId}/attach/{relatedResource}', 'ResourceAttachFormController@handle')->name('attach');
    Route::put('/{resourceId}/attach/{relatedResource}', 'ResourceAttachController@handle')->name('attach');
    Route::delete('/{resourceId}', 'ResourceDestroyController@handle')->name('destroy');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::resource('products', 'ProductController')->only(['index', 'show']);
Route::get('category/{category}', 'ProductController@category')->name('category.show');

// Cart
Route::post('cart/{product}', 'CartController@add')->name('cart.add');
Route::get('cart', 'CartController@show')->name('cart.show');
Route::delete('cart/{product}', 'CartController@remove')->name('cart.remove');

// Orders
Route::get('purchase/address', 'PurchaseController@addressCreate')->name('purchase.address.create');
Route::post('purchase/address', 'PurchaseController@addressStore')->name('purchase.address.store');
Route::get('purchase/success', 'PurchaseController@success')->name('purchase.success');
Route::get('purchase/error', 'PurchaseController@error')->name('purchase.error');
Route::resource('purchase', 'PurchaseController')->only(['store', 'create']);

app/CartItem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CartItem extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'product_id', 
        'quantity',
    ];

    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    protected $with = [
        'product',
    ];

    /**
     * All of the relationships to be touched.
     *
     * @var array
     */
    protected $touches = ['cart'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'quantity'      => 'decimal:2',
    ];

    /**
     * The associated cart
     * 
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function cart() 
    {
        return $this->belongsTo('App\Cart');
    }

    /**
     * The associated product
     * 
     * @return Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function product() 
    {
        return $this->belongsTo('App\Product');
    }

    /**
     * Total price for all the items in the cart item without discount
     *
     * @return float
     */
    public function getTotalAttribute()
    {
        return $this->product->price * $this->quantity;
    }

    /**
     * Total price for all the items in the cart item without discount
     *
     * @return float
     */
    public function getDiscountAttribute()
    {
        return $this->product->discount * $this->quantity;
    }

    /**
     * Total price for all the items in the cart item with discount
     *
     * @return float
     */
    public function getDiscountedTotalAttribute()
    {
        return $this->product->discounted_price * $this->quantity;
    }

    /**
     * Returns if the order item has a discount
     *
     * @return bool
     */
    public function getHasDiscountAttribute()
    {
        return ($this->discount_total != 0);
    }

    public function toOrderItem()
    {
        return [
            'price'      => $this->product->price,
            'discount'   => $this->product->discount,
            'product_id' => $this->product_id,
            'quantity'   => $this->quantity,
        ];
    }
}

resources/views/layouts/topcart/empty.blade.php
<div class="text-center px-3 py-5">
    <p>{{ __("Your cart is empty!") }}</p>
    <a href="{{ route('products.index') }}" class="btn btn-primary">{{ __('Explore our products') }}</a>
</div>

resources/views/layouts/topcart/icon.blade.php
@inject('cart', 'App\Services\CartManager')

<div class="dropdown">

    <a href="#" id="top-cart-trigger" class="mx-2 text-decoration-none" aria-label="{{ __('Show Cart') }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="material-icons" style="line-height: inherit;">shopping_cart</i>
        @if ($cart->items->count() > 0)
            <span class="badge badge-pill badge-primary align-top mx-n1">{{ $cart->items->count() }}</span>
        @endif
    </a>

    <div class="dropdown-menu dropdown-menu-right cart-dropdown border-0 shadow py-0" aria-labelledby="top-cart-trigger">
        <h2 class="dropdown-header">{{ __('Your Cart') }}</h2>
        <div class="list-group list-group-flush">
            @each('layouts.topcart.item', $cart->items, 'item', 'layouts.topcart.empty')
        </div>
        @if ($cart->items->count() > 0)
            <div class="card-footer">
                <div class="row">
                    <div class="fleft top-checkout-price py-1 col">{{ ReadableUnit::money($cart->discounted_total) }}</div>
                    <div class="col-auto">
                        <a href="{{ route('cart.show') }}" class="btn btn-primary button my-0 btn-small">{{ __('Show Cart') }}</a>
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>

resources/views/layouts/topcart/item.blade.php
<div class="list-group-item">
    <div class="media text-truncate">
        <img width="64" height="64" class="mr-3" src="{{ $item->product->thumbImage() }}" alt="{{ $item->product->name }}">
        <div class="media-body">
            <a href="{{ route('products.show', $item->product) }}" class="d-block stretched-link w-100">{{ $item->product->name }}</a>
            <span class="top-cart-item-price">
                @include('products.partials.price', ['product' => $item->product ])
            </span>
            <p class="top-cart-item-quantity mb-0">{{ ReadableUnit::quantity($item->quantity) }} {{__('Units')}}</p>
        </div>
    </div>
</div>